name: hypernetwork_resnet18
init_weights: True
in_dim: ~  # autofill later if None
num_classes: ~ # autofill later if None
in_channel_names: [red, green, blue]
separate_norm: FILL_LATER  # choice(True, False)
norm_type: FILL_LATER  # choice(batch_norm, layer_norm, instance_norm)
image_h_w: [32, 32]  ## used with norm_type="layer_norm"
z_dim: FILL_LATER
hidden_dim: FILL_LATER
separate_emb: true