name: cosine
convert_to_batch: True
params:
  t_initial: 30
  lr_min: 1.0e-6
  cycle_mul: 1.0
  cycle_decay: 0.5
  cycle_limit: 3
  warmup_t: 1
  warmup_lr_init: 1.0e-4
  warmup_prefix: False
  t_in_epochs: False
  noise_range_t: ~
  noise_pct: 0.67
  noise_std: 1.0
  noise_seed: 42
  k_decay: 1.0
  initialize: True