max_num_channels: FILL_LATER_IN_CODE
dim: FILL_LATER_IN_CODE
depth: 4
dim_head: 64
heads: 8
mlp_dim: 4
dropout: 0.0
use_cls_token: True
use_channel_tokens: True
init_channel_tokens: random  # only used when use_channel_tokens=True
