max_num_channels: FILL_LATER_IN_CODE
dim: FILL_LATER_IN_CODE
depth: 1
dim_head: 32
heads: 4
mlp_dim: 4
dropout: 0.1
use_cls_token: False
use_channel_tokens: True
init_channel_tokens: random  # only used when use_channel_tokens=True