name: shared_convnext
pretrained: True
pretrained_model_name: convnext_tiny.fb_in22k  ## convnext_tiny.fb_in22k_ft_in1k, convnext_small.in12k_ft_in1k
in_dim: ~  # autofill later if None
num_classes: ~ # autofill later if None
pooling: "avg"
temperature: 0.11111
learnable_temp: False
unfreeze_last_n_layers: -1
unfreeze_first_layer: True
first_layer: pretrained_pad_avg
reset_last_n_unfrozen_layers: False
use_auto_rgn: False