defaults:
  - train: ~
  - model: ~
  - scheduler: ~
  - optimizer: ~
  - dataset: ~
  - data_chunk: ~
  - logging: ~
  - hardware: ~
  - eval: ~
  - _self_

tag: ~

hydra:
  sweeper:
    params:
      train: random_instance
      data_chunk: full_3channels
      model: resnet18
      scheduler: multistep
      optimizer: sgd
      dataset: glob(*)
      logging: wandb
      hardware: default
      eval: default