max_num_channels: FILL_LATER_IN_CODE
dim: FILL_LATER_IN_CODE
depth: 2
dim_head: 16
heads: 4
mlp_dim: 4
dropout: 0.1
use_cls_token: True
use_channel_tokens: True
init_channel_tokens: zero  # only used when use_channel_tokens=True