batch_size: ~  ## None to auto set
dest_dir: ../STORE/adaptive_interface/snapshots/{FOLDER_NAME}/results
feature_dir: ../STORE/adaptive_interface/snapshots/{FOLDER_NAME}/features
root_dir: /projectnb/morphem/data_70k/ver2/morphem_70k_version2/
meta_csv_file: FILL_LATER
classifiers:
  - knn
  - sgd
classifier: PLACE_HOLDER
feature_file: features.npy
use_gpu: True
knn_metric: PLACE_HOLDER
knn_metrics:
  - l2 
  - cosine
clean_up: False
umap: True
only_eval_first_and_last: False