defaults:
  - train: ~
  - model: ~
  - scheduler: ~
  - optimizer: ~
  - dataset: ~
  - data_chunk: ~
  - logging: ~
  - hardware: ~
  - eval: ~
  - _self_

tag: ~

hydra:
  sweeper:
    params:
      train: random_instance
      data_chunk: hpa
      model: clip_vit
      scheduler: cosine
      optimizer: adamw
      dataset: hpa
      logging: wandb
      hardware: default
      eval: default